name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:

  build-and-push:
  
    runs-on: ubuntu-latest
    environment: build

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Push the image
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
